version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  backend:
    build:
      context: ./backend-spring
      dockerfile: Dockerfile
    container_name: realtime_editor_backend
    ports:
      - "8081:8080"
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/realtime_editor
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: realtime_editor_frontend
    ports:
      - "3000:5000"
    depends_on:
      - backend
    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_local
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  mongodb_data:
  jenkins_home:
    external: true
